package(default_visibility = ["//visibility:public"])


java_library(
name = "mainclass",
srcs = glob(["src/main/java/com/github/yeshamavani/*.java"]),
deps = ["//sharedlibrary:sharedlibrary"],
visibility = ["//visibility:public"]
)

